
input {
   kb_layout = it
                 
}

exec-once =  hypridle
exec-once = waybar
exec-once = flameshot
exec-once = hyprpaper

$mainMod = SUPER
$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5   
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5   
bind = $mainMod SHIFT, S, exec, flameshot
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow   
bind = $mainMod SHIFT, R, exec, hyprctl reload   
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exec, /home/ndrax/rofi/files/powermenu/type-1/powermenu.sh
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, L,  exec, hyprlock 

decoration {
    # Set global window transparency (Active, Inactive, Fullscreen)
    active_opacity = 0.55
    inactive_opacity = 0.55
    fullscreen_opacity = 0.55
    rounding = 15

    blur {
        enabled = true
        size = 5          # Blur radius
        passes = 3        # Number of blur iterations (higher = smoother but heavier)
        ignore_opacity = true  # CRITICAL: Keeps blur strong even when window is transparent
        new_optimizations = true
        vibrancy = 0.2    # Optional: Increases color saturation of the blur
        brightness = 0.6  # Optional: Slightly dims the blurred background
      
    
   
}
}   
