general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
    path = /home/ndrax/Pictures/wallpapers/black-hole.png
    blur_passes = 2 #2
    blur_size = 3 #8
    noise = 0.010
    contrast = 1.0
    brightness = 0.72
    vibrancy = 0.10
    vibrancy_darkness = 0.10
}

label {
    monitor =
    text = $TIME
    color = rgba(242, 243, 241, 0.90)
    font_size = 110
    font_family = JetBrains Mono Nerd Font Bold
    position = 0, 290
    halign = center
    valign = center
}

label {
    monitor =
    text = Welcome, $USER =]
    color = rgba(242, 243, 241, 0.72)
    font_size = 22
    font_family = JetBrains Mono Nerd Font
    position = 0, 175
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 340, 62
    outline_thickness = 3
    rounding = 7
    dots_rounding = 4
    dots_size = 0.18
    dots_spacing = 0.22
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.10)
    inner_color = rgba(255, 255, 255, 0.08)
    font_color = rgba(255, 255, 255, 0.95)
    fade_on_empty = false
    check_color = rgba(255, 80, 80, 0.50)
    fail_color = rgba(255, 30, 30, 1.0)
    fail_text = -[ ERROR ]-
    fail_timeout = 1000
    fail_transition = 0
    placeholder_text = <span foreground="##ffffff66"> Enter password </span>
    hide_input = false
    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:15000] fastfetch --logo none --structure "user:os"
    color = rgba(0, 255, 0, 0.50)
    font_size = 14
    font_family = JetBrains Mono Nerd Font
    position = 30, 30
    halign = left
    valign = bottom
}

label {
    monitor =
    text =   $LAYOUT
    color = rgba(0, 255, 0, 0.50) #rgba(242, 243, 241, 0.50)
    font_size = 14
    font_family = JetBrains Mono Nerd Font
    position = 0, -110
    halign = center
    valign = center
}
