splash = false
ipc = on

# 1. Preload the image (NO comma here)
preload = /home/ndrax/Pictures/wallpapers/map.png

# 2. Set the wallpaper (Comma BEFORE the path, empty monitor name = all monitors)
wallpaper = ,/home/ndrax/Pictures/wallpapers/map.png   
